/*
	Master UI Resource File
*/
#include "common.hpp"
#include "a3lcommon.hpp"

#include "halloweenshop.hpp"
#include "bankc4.hpp"
#include "shop_items.hpp"
#include "player_inv.hpp"
#include "gang.hpp"
#include "key_chain.hpp"
#include "impound.hpp"
#include "bank.hpp"
#include "veh_shop.hpp"
#include "shops.hpp"
#include "ui.hpp"
#include "admin_menu.hpp"
#include "cell_phone.hpp"
#include "cell_phone2.hpp"
#include "wanted_list.hpp"
#include "ticket.hpp"
#include "clothing.hpp"
#include "trunk.hpp"
#include "spawnSelection.hpp"
#include "chop_shop.h"
#include "pInteraction.h"
#include "deathScreen.h"
#include "vehicleShop.h"
#include "settings.h"
#include "federalReserve.h"
#include "tablet.hpp"
#include "smsmenu.hpp"
#include "arrestmenu.hpp"
#include "veh_repaint.hpp"
#include "channel.hpp"
#include "compensate.hpp" 
//Icaruk
#include "menuLoteria.hpp"
#include "menuTransporte.hpp"
#include "menuMateriales.hpp"
#include "menuBanco.hpp"
#include "menuCrafteo.hpp"
#include "menuRepostar.hpp"
#include "menuElectricidad.hpp"
#include "menuDemanda.hpp"
#include "menuSuministros.hpp"
#include "TestDroInv.hpp"
#include "TestDroNeg.hpp"
#include "TestDroPosMar.hpp"
#include "TestDroPosHer.hpp"
#include "TestDroPosCoc.hpp"